**Problem StatementProblem Statement 
1:Write a function so that the columns of the output matrix are powers of the inputvector.The order of the powers is determined by the increasing boolean argument. Specifically, when increasing is False, the i-th output column is the input vector raised element-wise to the power of N -i -1.**

HINT:  Such  a  matrix  with  a  geometric  progression  in  each  row  is  named  for  Alexandre-Theophile Vandermonde.

In [1]:
import numpy as np

In [15]:
m=list(map(int,input().strip().split()))
vect = np.array(m)

2 3 1 4


In [19]:
np.vander(vect)

array([[ 8,  4,  2,  1],
       [27,  9,  3,  1],
       [ 1,  1,  1,  1],
       [64, 16,  4,  1]])

In [16]:
n=5
np.vander(vect,n)

array([[ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [  1,   1,   1,   1,   1],
       [256,  64,  16,   4,   1]])

In [17]:
np.vander(vect,n,increasing=False)

array([[ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [  1,   1,   1,   1,   1],
       [256,  64,  16,   4,   1]])

In [18]:
np.vander(vect,n,increasing=True)

array([[  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   1,   1,   1,   1],
       [  1,   4,  16,  64, 256]])

**Q:Write a function to find moving average in an array over a window:Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.**

In [25]:
def moving_avg(arr,window):
    mov_avg=[]
    for i in range(0,len(arr)-window+1):
        s=0
        s=sum(arr[i:i+window])
        mov_avg.append(s//window)
    return mov_avg

arr=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
print(moving_avg(arr,4))

[25, 35, 45, 55, 65, 75, 85]


In [26]:
arr = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] 
moving_avg(arr,3)

[5, 4, 5, 6, 9, 28, 49, 72, 84, 93, 116]